<?php
require "inc/report-function.inc.php"; // configuration file
connectDB(); // Connect to database

$facilityName = isset($_GET['facilityName']) ? $_GET['facilityName'] : "";
$results = fetchEmails($facilityName);

global $db;
if (!$results) die("Error fetching items from DB: " . $db->error);
$pageTitle = "Report 10 - Emails Sent"; // Dynamic page title
include "inc/header.inc.php"; // header
?>
    <div class="row mt-4">
        <div class="col-12">
            <h2><?= $pageTitle ?></h2>
            <h6 class="text-justify">List the emails generated by a given facility. The results should be displayed in ascending order by the date of the emails.</h6>
            <hr>
        </div>

        <div class="col-12 mb-3">
            <form action="" method="GET" class="form-inline border p-2">
                <div class="form-group pl-2">
                    <label for="facilityName" class="pr-2">Facility Name:</label>
                    <input type="text" class="form-control" name="facilityName" id="facilityName">
                </div>
                <button type="submit" class="btn btn-primary ml-2">Filter</button>
            </form>
        </div>

        <div class="table-responsive col-12">
            <table class="table table-hover table-striped table-bordered">
                <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Date</th>
                    <th>Facility</th>
                    <th>Sender</th>
                    <th>Receiver</th>
                    <th>Subject</th>
                    <th>Body</th>
                </tr>
                </thead>
                <tbody>
                <?php while ($row = $results->fetch_assoc()) { ?>
                    <tr>
                        <td><?= $row['id']; ?></td>
                        <td><?= $row['date']; ?></td>
                        <td><?= $row['name']; ?></td>
                        <td><?= $row['sender']; ?></td>
                        <td><?= $row['receirver']; ?></td>
                        <td><?= $row['subject']; ?></td>
                        <td><?= $row['body']; ?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>

<?php include "inc/footer.inc.php"; //footer ?>